### PR TITLE
Separate data list reference support

### PR DESCRIPTION
**Pull request by Defeatomizer**
This is a spin-off of block state properties saga, adding support for using external data lists as the source of values for enum block state properties.

### CODE REVIEW

**Comment by Defeatomizer** [comment]
изображение

**Review by KlemenDEV — COMMENTED** [review]
Translation text for stats screen is likely missing for noteblockinstruments

**Review by KlemenDEV — CHANGES_REQUESTED** [review]
This is also missing mappings in templates. Right now you kinda hacked it with mapping key values. Instead you should make two mapping tables for Java and JSON and properly handle this in templates.

_default value handing is non-existent right now if one selects value in 1.21.1 and then switches to 1.20.1 generator. The game will just crash when trying to load non-existent enum from string

**Comment by Defeatomizer** [comment]
> Translation text for stats screen is likely missing for noteblockinstruments

That was intentional to some degree as right now this list is not used on its own.

**Comment by KlemenDEV** [comment]
> That was intentional to some degree as right now this list is not used on its own.

I think it is added automatically to the list, though

**Comment by Defeatomizer** [comment]
> Instead you should make two mapping tables for Java and JSON and properly handle this in templates.

In the new list? So the other one would be the value registry name (same as DL entry name)?

**Comment by KlemenDEV** [comment]
Yes, see e.g. biomes for example.

Technically you can only provide one mapping table for now, that covers registry_names, if the material PR won't happen that soon, so we don't keep unused stuff in the core master branch.

**Comment by Defeatomizer** [comment]
Should I add extra mapping table for `noteblockinstruments` reference to block state properties mappings? If yes, should it be put before class name, after class name, or maybe together in some way?

**Comment by KlemenDEV** [comment]
Since it is only one property for now, you can just hardcode check in block.java.ftl for this case

**Review by KlemenDEV — APPROVED** [review]
LG™, you can merge and we can continue on the main PR

**Pull request merged**
